# Generated by Django 5.2.12 on 2026-04-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('RECEPTIONIST', 'Receptionist'), ('HR', 'HR Manager'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('LABORATORIAN', 'Laboratorian/Reporter'), ('ACCOUNTANT', 'Accountant')], default='RECEPTIONIST', max_length=20),
        ),
    ]
