# Generated by Django 5.2.12 on 2026-04-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0002_prescription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('SUPPOSITORY', 'Suppository'), ('OTHER', 'Other')], default='TABLET', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DispensingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_by', models.CharField(blank=True, help_text='Staff name', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensings', to='prescriptions.prescription')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensings', to='pharmacy.medicine')),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
    ]
