# Generated by Django 5.2.12 on 2026-04-29 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medicine_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('brand_names_url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generic Medicine',
                'verbose_name_plural': 'Generic Medicines',
            },
        ),
        migrations.CreateModel(
            name='BrandMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=500)),
                ('dosage_form', models.CharField(blank=True, max_length=255)),
                ('strength', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, max_length=500)),
                ('pack_size_price', models.TextField(blank=True)),
                ('brand_detail_url', models.URLField(unique=True)),
                ('source_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='pharmacy.genericmedicine')),
            ],
            options={
                'verbose_name': 'Brand Medicine',
                'verbose_name_plural': 'Brand Medicines',
            },
        ),
    ]
