# Generated by Django 5.2.12 on 2026-04-03 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_allergies_patient_medical_history_vitalsign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOPICAL', 'Topical'), ('RECTAL', 'Rectal'), ('INHALATION', 'Inhalation'), ('SUBLINGUAL', 'Sublingual')], default='ORAL', max_length=50)),
                ('administered_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'NURSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_administrations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='patients.patient')),
            ],
            options={
                'ordering': ['-administered_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'NURSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
