# Generated by Django 5.2.12 on 2026-04-03 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorschedule'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='List known allergies, one per line'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Past medical history, chronic conditions, surgeries'),
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.PositiveIntegerField(help_text='Systolic BP (mmHg)')),
                ('blood_pressure_diastolic', models.PositiveIntegerField(help_text='Diastolic BP (mmHg)')),
                ('heart_rate', models.PositiveIntegerField(help_text='Heart rate (bpm)')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Temperature (°F)', max_digits=4)),
                ('respiratory_rate', models.PositiveIntegerField(help_text='Respiratory rate (breaths/min)')),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, help_text='SpO2 (%)', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight (kg)', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height (cm)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_records', to='doctors.doctor')),
            ],
            options={
                'verbose_name_plural': 'Vital Signs',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
