# Generated by Django 5.2.12 on 2026-04-03 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField(help_text='Consultation start time')),
                ('end_time', models.TimeField(help_text='Consultation end time')),
                ('break_start', models.TimeField(blank=True, help_text='Break start time (optional)', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Break end time (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this schedule')),
                ('max_patients', models.PositiveIntegerField(default=20, help_text='Maximum patients per day (0 = unlimited)')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
            options={
                'verbose_name_plural': 'Doctor Schedules',
                'ordering': ['doctor', 'day_of_week'],
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
    ]
